const $=id=>document.getElementById(id);let words=[],index=-1,playing=false,done=false,timer=null,wpm=300,speechEpoch=0;const speechAvailable='speechSynthesis' in window&&'SpeechSynthesisUtterance' in window;
function duration(n){const s=Math.ceil(n*60/wpm);return s>=60?`${Math.floor(s/60)} min ${s%60} sec`:`${s} sec`}
function render(){ $('count').textContent=`${words.length.toLocaleString()} words`;$('position').textContent=`${Math.max(0,index+1)} / ${words.length} words`;$('remaining').textContent=`${duration(done?0:words.length-Math.max(0,index))} remaining`;const p=words.length?Math.max(0,index+1)/words.length*100:0;$('fill').style.width=p+'%';document.querySelector('[role=progressbar]').setAttribute('aria-valuenow',Math.round(p));$('word').textContent=index>=0?words[index]:'Ready.';$('play').disabled=!words.length;$('restart').disabled=!words.length;$('stop').disabled=!words.length;$('back').disabled=index<1;$('play-label').textContent=playing?'Pause':done?'Read again':index>=0?'Resume':'Start reading';$('play-icon').innerHTML=playing?'<path d="M8 5v14M16 5v14" stroke-width="4"/>':'<path d="m8 5 11 7-11 7Z" fill="currentColor" stroke="none"/>';$('status').textContent=playing?'In the flow':done?'Reading complete':index>=0?'Paused':'Ready when you are';}
function cancel(){clearTimeout(timer);speechEpoch++;if(speechAvailable)window.speechSynthesis.cancel()}
function pause(){cancel();playing=false;render()}
function finish(){if($('loop').checked){index=0;render();schedule()}else{playing=false;done=true;render()}}
function tick(){timer=setTimeout(()=>{if(!playing)return;if(index>=words.length-1){finish();return}index++;render();tick()},60000/wpm)}
function speak(){const epoch=++speechEpoch,start=index,chunk=words.slice(start,start+40),offsets=[];let offset=0;chunk.forEach(w=>{offsets.push(offset);offset+=w.length+1});const utterance=new SpeechSynthesisUtterance(chunk.join(' '));utterance.rate=Math.max(.3,Math.min(4,wpm/180));utterance.onboundary=e=>{if(epoch!==speechEpoch||!playing)return;let local=0;for(let i=0;i<offsets.length;i++){if(offsets[i]<=e.charIndex)local=i}index=start+local;render()};utterance.onend=()=>{if(epoch!==speechEpoch||!playing)return;index=start+chunk.length-1;render();if(index>=words.length-1)finish();else{index++;render();speak()}};utterance.onerror=()=>{if(epoch!==speechEpoch||!playing)return;pause();$('voice-note').textContent='Voice unavailable. Turn off Read aloud to continue.'};window.speechSynthesis.speak(utterance)}
function schedule(){if($('voice').checked&&speechAvailable)speak();else tick()}
function toggle(){if(!words.length)return;if(playing){pause();return}if(done||index<0){index=0;done=false}playing=true;render();schedule()}
function setText(text){pause();$('text').value=text;words=text.trim()?text.trim().split(/\s+/u):[];index=-1;done=false;render()}
function setSpeed(value){const n=Number(value);if(!Number.isFinite(n))return;wpm=Math.max(50,Math.min(1200,Math.round(n)));$('wpm').value=wpm;$('speed').value=wpm;if(playing){cancel();schedule()}render()}
function back(){const resume=playing;pause();index=Math.max(0,index-10);done=false;render();if(resume){playing=true;render();schedule()}}
function stop(){pause();index=-1;done=false;render()}
$('text').addEventListener('input',e=>setText(e.target.value));$('edit').onclick=()=>{pause();$('text').focus()};$('clear').onclick=()=>{setText('');$('text').focus()};$('sample').onclick=()=>setText('There is a rhythm to reading. A small space between one idea and the next. When the distractions fall away, all that remains is the word in front of you. Let your eyes settle. Let the words come to you. Start slowly, find a comfortable pace, and adjust as you go. You do not have to race to the finish. Sometimes, the best way to take in more is to focus on less. One word. One moment. One idea at a time.');$('play').onclick=toggle;$('restart').onclick=()=>{stop();toggle()};$('stop').onclick=stop;$('back').onclick=back;$('speed').oninput=e=>setSpeed(e.target.value);$('wpm').onchange=e=>setSpeed(e.target.value);$('voice').onchange=()=>{if(playing){cancel();schedule()}};if(!speechAvailable){$('voice').disabled=true;$('voice-note').textContent='Read aloud is unavailable in this browser.'}document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|BUTTON/.test(e.target.tagName)||e.target.isContentEditable)return;if(e.code==='Space'){e.preventDefault();toggle()}if(e.code==='ArrowLeft'&&words.length){e.preventDefault();back()}if(e.code==='Escape')stop()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)pause()});render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_reader',description:'Set the reader text and words per minute. Pauses and resets reading.',inputSchema:{type:'object',properties:{text:{type:'string'},wpm:{type:'integer',minimum:50,maximum:1200}},required:['text','wpm'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(typeof input.text!=='string'||!Number.isInteger(input.wpm)||input.wpm<50||input.wpm>1200)throw new Error('Provide text and a WPM between 50 and 1200.');setText(input.text);setSpeed(input.wpm);return {words:words.length,wpm,status:'ready'}}})).catch(()=>{})}catch{}}
